### ISSUE TITLE
How do use with HTML Comments?

### ISSUE THREAD

**Issue by lexman1958** [lovebirdsx/better-comments-enhanced#1]
Hi,

I love this extension but disappointed in one aspect. I could set the color of the comment for other languages except HTML. The HTML comments is "<?-- -->. Where do i set the color for the comment similar to "// *" or "//?".??

Appreciate some help.

**Comment by murugappanrm** [comment]
Why is there no answer for this?

**Comment by lovebirdsx** [comment]
> Hi,
> 
> I love this extension but disappointed in one aspect. I could set the color of the comment for other languages except HTML. The HTML comments is "<?-- -->. Where do i set the color for the comment similar to "// *" or "//?".??
> 
> Appreciate some help.

![image](https://github.com/lovebirdsx/better-comments-enhanced/assets/5227960/f622fc7b-1e77-4a03-8afb-6987673db2c2)
